/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drme;
import javax.swing.*;
/**
 *
 * @author Sarp
 */
public class PatientSignUpPanel extends javax.swing.JPanel {
public String name, surname, age, chronic, ssn, contact, adress, eContact;
public String blood = "A Rh+";
public String gender = "Male";
    /**
     * Creates new form PatientSignUpPanel
     */
    public PatientSignUpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        ChronicField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        AdressField = new javax.swing.JTextField();
        EmergencyContactField = new javax.swing.JTextField();
        SSNField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        BloodComboBox = new javax.swing.JComboBox();
        GenderComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Name :");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Surname :");

        jLabel3.setText("Age :");

        jLabel4.setText("Gender :");

        jLabel5.setText("Blood Type :");

        jLabel6.setText("Chronic Illnesses(Enter\"/\" seperated):");

        jLabel7.setText("SSN :");

        jLabel8.setText("Contact Number :");

        jLabel9.setText("Adress : ");

        jLabel10.setText("Emergency Contact :");

        SurnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameFieldActionPerformed(evt);
            }
        });

        AgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeFieldActionPerformed(evt);
            }
        });

        ChronicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChronicFieldActionPerformed(evt);
            }
        });

        ContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactFieldActionPerformed(evt);
            }
        });

        AdressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressFieldActionPerformed(evt);
            }
        });

        EmergencyContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyContactFieldActionPerformed(evt);
            }
        });

        SSNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNFieldActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        BloodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A Rh+", "A Rh-", "B Rh+", "AB Rh+", "AB Rh-", "0 Rh+", "0 Rh-" }));
        BloodComboBox.setSelectedItem("<select>");
        BloodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodComboBoxActionPerformed(evt);
            }
        });

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        GenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdressField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ContactField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SSNField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ChronicField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BloodComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 80, Short.MAX_VALUE)
                                .addComponent(GenderComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SurnameField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NameField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(EmergencyContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BloodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ChronicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SSNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(AdressField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmergencyContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitButton)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
        name = NameField.getText();
    }//GEN-LAST:event_NameFieldActionPerformed

    private void SurnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameFieldActionPerformed
        // TODO add your handling code here:
        surname = SurnameField.getText();
    }//GEN-LAST:event_SurnameFieldActionPerformed

    private void AgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeFieldActionPerformed
        // TODO add your handling code here:
        age = AgeField.getText();
    }//GEN-LAST:event_AgeFieldActionPerformed

    private void GenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboBoxActionPerformed
        // TODO add your handling code here:
            gender = (String) GenderComboBox.getSelectedItem();
    }//GEN-LAST:event_GenderComboBoxActionPerformed

    private void BloodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodComboBoxActionPerformed
        // TODO add your handling code here:
            blood = (String) BloodComboBox.getSelectedItem();
    }//GEN-LAST:event_BloodComboBoxActionPerformed

    private void ChronicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChronicFieldActionPerformed
        // TODO add your handling code here:
        chronic = ChronicField.getText();
    }//GEN-LAST:event_ChronicFieldActionPerformed

    private void SSNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNFieldActionPerformed
        // TODO add your handling code here:
        ssn = SSNField.getText();
    }//GEN-LAST:event_SSNFieldActionPerformed

    private void ContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactFieldActionPerformed
        // TODO add your handling code here:
        contact = ContactField.getText();
    }//GEN-LAST:event_ContactFieldActionPerformed

    private void AdressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressFieldActionPerformed
        // TODO add your handling code here:,
        adress = AdressField.getText();
    }//GEN-LAST:event_AdressFieldActionPerformed

    private void EmergencyContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyContactFieldActionPerformed
        // TODO add your handling code here:
        eContact = EmergencyContactField.getText();
    }//GEN-LAST:event_EmergencyContactFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        name = NameField.getText();
        surname = SurnameField.getText();
        age = AgeField.getText();
        gender = (String) GenderComboBox.getSelectedItem();
        blood = (String) BloodComboBox.getSelectedItem();
        chronic = ChronicField.getText();
        ssn = SSNField.getText();
        contact = ContactField.getText();
        adress = AdressField.getText();
        eContact = EmergencyContactField.getText();

        DBConnect con = new DBConnect("patients");
        int[] arr = con.getIDs();
        
        Patient patient;
        int a = Integer.parseInt(age);
        if(arr.length<1)
        {
            patient = new Patient(1000, name, surname, a, ssn, blood, gender, chronic, contact, eContact, adress);
            JOptionPane.showMessageDialog(null,"Your ID  is 1000");
        }
        else
        {
            patient = new Patient(arr[arr.length-1]+1, name, surname, a, ssn, blood, gender, chronic, contact, eContact, adress);
            JOptionPane.showMessageDialog(null,"Your ID  is " + (arr[arr.length-1]+1));
        }
                con.addPatient(patient);

    }//GEN-LAST:event_SubmitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AdressField;
    public javax.swing.JTextField AgeField;
    public javax.swing.JComboBox BloodComboBox;
    public javax.swing.JTextField ChronicField;
    public javax.swing.JTextField ContactField;
    public javax.swing.JTextField EmergencyContactField;
    public javax.swing.JComboBox GenderComboBox;
    public javax.swing.JTextField NameField;
    public javax.swing.JTextField SSNField;
    private javax.swing.JButton SubmitButton;
    public javax.swing.JTextField SurnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
