/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drme;
import javax.swing.*;
/**
 *
 * @author Sarp
 */
public class SignUpPanel extends javax.swing.JPanel {

    String str = "";
    /**
     * Creates new form SignUpPanel
     */
    public SignUpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientRadio = new javax.swing.JRadioButton();
        HealthOfficerRadio = new javax.swing.JRadioButton();
        DoctorRadio = new javax.swing.JRadioButton();
        NextButton = new javax.swing.JButton();

        PatientRadio.setText("I am a patient");
        PatientRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientRadioActionPerformed(evt);
            }
        });

        HealthOfficerRadio.setText("I am a health officer");
        HealthOfficerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthOfficerRadioActionPerformed(evt);
            }
        });

        DoctorRadio.setText("I am a doctor");
        DoctorRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorRadioActionPerformed(evt);
            }
        });

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HealthOfficerRadio)
                    .addComponent(DoctorRadio)
                    .addComponent(PatientRadio))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(PatientRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DoctorRadio)
                .addGap(18, 18, 18)
                .addComponent(HealthOfficerRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PatientRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRadioActionPerformed
        // TODO add your handling code here:
        str = "patient";
    }//GEN-LAST:event_PatientRadioActionPerformed

    private void DoctorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorRadioActionPerformed
        // TODO add your handling code here:
        str = "doctor";
    }//GEN-LAST:event_DoctorRadioActionPerformed

    private void HealthOfficerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthOfficerRadioActionPerformed
        // TODO add your handling code here:
        str = "officer";
    }//GEN-LAST:event_HealthOfficerRadioActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        
        if (str.equalsIgnoreCase("patient"))
        {
            JFrame frame = new JFrame("Patient Sign Up");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(new PatientSignUpPanel());
            frame.pack();
            frame.setVisible(true);
        }
        
        if (str.equalsIgnoreCase("doctor"))
        {
            JFrame frame = new JFrame("Doctor Sign Up");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(new DoctorSignUpPanel());
            frame.pack();
            frame.setVisible(true); 
        }
        
        if (str.equalsIgnoreCase("officer"))
        {
            new OfficerSignUp();
            
            //JFrame frame = new JFrame("Officer Sign Up");
            //frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            //frame.getContentPane().add(new OfficerSignUpPanel());
            //frame.pack();
            //frame.setVisible(true); 
        }
        
        
    }//GEN-LAST:event_NextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DoctorRadio;
    private javax.swing.JRadioButton HealthOfficerRadio;
    private javax.swing.JButton NextButton;
    private javax.swing.JRadioButton PatientRadio;
    // End of variables declaration//GEN-END:variables
}
